### ISSUE TITLE
Feature: User can record workout sets, reps, and weights within a workout session

### ISSUE THREAD

**Issue by damien-martinez** [damien-martinez/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can record workout sets, reps, and weights within a workout session. User will also be able to add other workouts/exercises to the session and add data to that particular workout/exercise.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will type in the weight they used for that specific workout on that specific set. User will type in how many reps they did for that specific workout on that specific set. User will be able to choose from a dropdown of workouts/exercises to add to the session. User will be able to add data to added workout/exercises as well.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="780" alt="Screen Shot 2022-04-13 at 11 37 42 AM" src="https://user-images.githubusercontent.com/40590740/163247831-ae038c7d-882b-4518-8a79-1bdeae596b32.png">
<img width="782" alt="Screen Shot 2022-04-13 at 11 38 05 AM" src="https://user-images.githubusercontent.com/40590740/163247853-f3eac260-f28b-4bc1-b08f-0054f3b43a36.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to add the new SQL script exported from de designer
- [x] Change .env.example to reflect name of database
- [x] Make sure postgreSQL is running
- [x] Createdb finalProject
- [x] Make sure db is up pgweb --db=finalProject (http://localhost:8081)

### ☁️ Server

- [x] Update `server/index.js` to be able to handle post requests of workout session info. 
- [x] Within post request, query db so that data is inserted in the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render the workout session page
- [x] A listener event that will add sets after "add set" is clicked on
- [x] Update component to change value of inputs on update 
- [x] Create a component to listen for click to open modal that will show new workouts/exercises
- [x] create a component to render a drop-down list of workouts 
- [x] Once user clicks on a drop-down item and hits submit button, modal will close and the page will re-render with a new workout/exercise.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
