### ISSUE TITLE
Feature: User can edit and/or delete a workout set and/or workout exercise from a session

### ISSUE THREAD

**Issue by damien-martinez** [damien-martinez/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete specific sets or exercises in a given workout session.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a user were to add an exercise or a set to their workout session and the user no longer needs/wants said exercise or set, the user can remove it from the workout session.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="245" alt="Screen Shot 2022-05-05 at 8 10 47 PM" src="https://user-images.githubusercontent.com/40590740/167061085-a364f7d3-7367-47cc-85c6-cd8c397fa75c.png">
<img width="666" alt="Screen Shot 2022-05-05 at 8 11 00 PM" src="https://user-images.githubusercontent.com/40590740/167061099-11ae031c-b4b7-4d61-b6c8-887b3029377f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update component to render a button per set that will remove the set when clicked.
- [x] Create a function that will trigger when button is clicked. Within function, will remove the set from the workout object
- [x] Add a button per exercise that will remove an entire workout session when clicked.
- [x] Create a function that will trigger when button is clicked. Within function, will remove exercise from workouts array

### 🧑‍⚕️ Clean Up

- [x] Click buttons to test if buttons work
- [x] Remove all exercises and sets to test if any errors occur.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
