### ISSUE TITLE
Feature: User can see duration of workout session

### ISSUE THREAD

**Issue by damien-martinez** [damien-martinez/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see the duration of their workout session (visible in hours, minutes, and seconds). The time (in minutes) will later be saved so that user can use in other features. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user is in workout session there will be a dynamic timer that shows the user how long they have been working out. User can also pause and start the timer.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="549" alt="Screen Shot 2022-04-16 at 5 55 44 PM" src="https://user-images.githubusercontent.com/40590740/163695824-d88f4892-588b-4221-b0f6-c40f512a6424.png">
<img width="559" alt="Screen Shot 2022-04-16 at 5 55 48 PM" src="https://user-images.githubusercontent.com/40590740/163695827-6e9ca32f-a808-4cc5-9595-9ddf21d89aa1.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component that will start a timer function
- [x] Add some math operations that will convert the total seconds to hours, minutes, and seconds
- [x] Update component to increment the timer shown in UI for every second that is passed
- [x] Add functionality that will pause and start the timer again

### 🧑‍⚕️ Clean Up

- [x] Test the timer by letting some time pass. Every 60 seconds, the minute should increment
- [x] Test by hard coding the seconds value within the state
- [x] Test the pause and start feature
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
