### ISSUE TITLE
Feature: User can save the data of completed workout session

### ISSUE THREAD

**Issue by damien-martinez** [damien-martinez/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a completed workout. Saved data includes the name of the workout session, the name of the workout exercises, the set number, the pounds of the set, and the reps of the set.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will hit the finish button. User will be prompted to name the workout session. When user hits finish, the workout session data will be saved to the database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="880" alt="Screen Shot 2022-04-16 at 6 02 04 PM" src="https://user-images.githubusercontent.com/40590740/163695919-322f4223-9a26-4a70-a2bc-9cb295722ba5.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update database so that the session table receives new data from new session
- [x] Update database so that sessionWorkouts table recieves new data from new session

### ☁️ Server

- [x] Update `server/index.js` to have a post route that takes all of the workout session info to save to database
- [x] Add data to the JSON file to test HTTPIE to see if data gets stored correctly 
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a post request so that server sends info to the database
- [x] Update components so that all info gets lifted to the WoukoutSession component 
- [x] Update components to hold all info and store into arrays to easily send over the data
- [x] Clear states

### 🧑‍⚕️ Clean Up

- [x] Try to trigger errors when adding data to fields and submitting
- [x] Fix all errors found
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
