### ISSUE TITLE
Feature: User can see how many times they work out per month on a bar graph

### ISSUE THREAD

**Issue by damien-martinez** [damien-martinez/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see how many times they work out per month a a bar graph. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on Profile tab, user will be taken to the profile page. Once at the profile page, user will be able to see a graph that shows the amount of times the user has worked out per month.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="876" alt="Screen Shot 2022-04-16 at 6 26 33 PM" src="https://user-images.githubusercontent.com/40590740/163696389-312bba3f-b889-4b32-8f85-568bf1995406.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a render page method that decides what page to render
- [x] Create a method that listens for hashchange
- [x] Create a homepage component 
- [x] Create a component to render profile page
- [x] Create a component that will render the chart
- [x] Create functionality for when user clicks cancel workout. State should clear, time will pause, and user should be taken back to homepage
- [x] Create a get fetch request update that will grab all the data from the Session table

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
