### ISSUE TITLE
Feature: User can see their best sets per workout on a line graph

### ISSUE THREAD

**Issue by damien-martinez** [damien-martinez/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see their best set based on a line graph based on an exercise they choose.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to choose their exercise from a dropdown menu. Based on what exercise they choose, user will see their best sets during a given workout session.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="876" alt="Screen Shot 2022-04-16 at 6 26 33 PM" src="https://user-images.githubusercontent.com/40590740/163696429-c18237d4-f112-4722-adfa-7fb2664a5742.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to get exercise data based on workoutId
- [x] Test with HTTPie to retrieve all exercise data based on workoutId
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add to component to render a dropdown to enable to choose a specific exercise.
- [x] Once drop-down is chosen and submitted, create a function that will request data from the backend to pull exercise data
- [x] Create a function that manipulated the data so that it can be graphed using chartJS
- [x] Graph data

### 🧑‍⚕️ Clean Up

- [x] Test to see if multiple graphs can be created
- [x] Add another workout session and test if new data is included in graph. 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
